var seenAfter = 12;
console.log(typeof seenAfter);
var promise ="i love my country. i love my land";
console.log(promise.toUpperCase());
var promise ="THIS IS MY NEW BRAND WATCH";
console.log(promise.toLowerCase());
var promise ="i love my country. i love my land";
console.log(promise.indexOf('love'));
var promise ="i love my country. i love my land";
console.log(promise.split('love'));
var number1 = 25;
var number2 = '24.6';

number2 = parseInt(number2);
console.log(number1 + number2);
var number1 = 0.508;
var number2 = 0.56;
var total = number1 + number2;
total = total.toFixed(5);
console.log(total);
var price1 = 23356;
var price2 = 46665387;
price2++;
console.log(price2);  
var name1 = 'justin';
name2 = 'biber';
result = name1 + ' ' + name2;
console.log(result);
var number = -1723;
var absoluteNumber = Math.abs(number);
console.log(absoluteNumber);
var number = 5.49999;
var result = Math.floor(number);
console.log(result);
var number = Math.random() * 100;
var result = Math.round(number);
console.log(result);